// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs1wO5Ma-izv13NOzegpDIBMKW767dE3E',
    appId: '1:101948232468:web:d4474cc1f08a15c126e801',
    messagingSenderId: '101948232468',
    projectId: 'flluter-push-notifications',
    authDomain: 'flluter-push-notifications.firebaseapp.com',
    storageBucket: 'flluter-push-notifications.appspot.com',
    measurementId: 'G-K4HKYRE8V1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClvNzWajMMrFjnEKGl3xOMleULaaAcL1Y',
    appId: '1:101948232468:android:b8c485204773113526e801',
    messagingSenderId: '101948232468',
    projectId: 'flluter-push-notifications',
    storageBucket: 'flluter-push-notifications.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgLNdjEbPss0hVdMxPWCJAEv77iQuWFrY',
    appId: '1:101948232468:ios:6c89b8b22dcf419026e801',
    messagingSenderId: '101948232468',
    projectId: 'flluter-push-notifications',
    storageBucket: 'flluter-push-notifications.appspot.com',
    iosClientId:
        '101948232468-gngiig53iccgiqbk25anfsq9njjtd7c6.apps.googleusercontent.com',
    iosBundleId: 'com.loopsdelivery',
  );
}
